version: "3.9"
services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: nextuser
      POSTGRES_PASSWORD: nextpass
      POSTGRES_DB: nextapp
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"        # ホスト → コンテナ転送（ローカル開発用）

  web:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://nextuser:nextpass@db:5432/nextapp
      NODE_ENV: production
    ports:
      - "3000:3000"        # http://localhost:3000 で確認
    # 開発ビルドにしたいときは ↓ を付けて live reload
    # volumes:
    #   - .:/app
    #   - /app/node_modules  # node_modules を上書きしないための隠し volume

volumes:
  db-data:
