import type { Metadata } from "next";
import { Inter } from 'next/font/google'
import "./globals.css";
import { ReactNode } from 'react';

const inter = Inter({
  subsets: ['latin'],      // ← そのまま
  variable: '--font-inter' // CSS 変数名は自由
})

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "WeiseProjects",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="min-h-screen bg-zinc-50 text-zinc-900 antialiased">
        {children}
      </body>
    </html>
  );
}
