import type { Metadata } from "next";
import { Inter } from 'next/font/google'
import "./globals.css";
import { ReactNode } from 'react';
import Sidebar from '@/components/Sidebar';
import '../styles/project-card.css';

export const dynamic = 'force-dynamic';

const inter = Inter({
  subsets: ['latin'],      // ← そのまま
  variable: '--font-inter' // CSS 変数名は自由
})

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "WeiseProjects",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="flex bg-[#23262B] text-zinc-100">
        {/* 左に常駐させる */}
        <Sidebar />
        <main className="flex-1 h-screen overflow-y-auto">{children}</main>
      </body>
    </html>
  );
}
